name: Main

on:
  push:
    branches-ignore: "release*"
  repository_dispatch:
    types: ["blt-jenkins"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo-env
        env:
          RELEASE_TAG: ${{ github.event.client_payload.image_tag }}
        run: |
          make echo-env
      - name: Ref
        if: github.ref == 'refs/heads/master'
        run: echo $GITHUB_REF
