name: Main

on:
  push:
    branches-ignore: "release*"
  repository_dispatch:
    types: ["blt-jenkins"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo $GITHUB_REF
      - name: Ref
        if: github.ref == 'refs/heads/master'
        run: echo $GITHUB_REF
